'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Products
    Public Property ID As Integer
    Public Property CategoryID As Nullable(Of Integer)
    Public Property name As String
    Public Property stock As Nullable(Of Integer)
    Public Property Price As Nullable(Of Decimal)
    Public Property activity As Nullable(Of Boolean)

    Public Overridable Property Orders As ICollection(Of Orders) = New HashSet(Of Orders)
    Public Overridable Property ProductCategorys As ProductCategorys

End Class
