//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HusoBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int ID { get; set; }
        public string TCIDNumber { get; set; }
        public string name { get; set; }
        public string Surname { get; set; }
        public string CardNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> ExpMonth { get; set; }
        public Nullable<int> ExpYear { get; set; }
        public string CCV { get; set; }
    }
}
