//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HusoBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosCustomers
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string MerchantID { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    }
}
